Repository PugachA/UnmannedAerialVehicle, pull requests merged in 2020-11, with the labels that each got.

#113 [Logger] Added support for work without SD card
  Logger/Core/Src/main.cpp
Labels: ERS

#123 [Plane] Add roll omega control
  Plane/Core/Src/main.cpp
  Plane/RC_read Debug.launch
Labels: AFCS

#129 [Plane] changeed clock source to hse
  Plane/Core/Inc/stm32f4xx_hal_conf.h
  Plane/Core/Src/main.cpp
  Plane/Plane.ioc
Labels: Critical
