Repository PugachA/UnmannedAerialVehicle, pull requests merged in 2020-10, with the labels that each got.

#79 [BugFix] Устранение проблемы неверной длины импульсов и вызова САС
  .gitignore
  Libraries/Math/Math.cpp
  Libraries/Math/Math.h
  Libraries/RcChannel/RcChannel.cpp
  Libraries/Sum/sum.cpp
  Libraries/Sum/sum.h
  Plane/.cproject
  Plane/.mxproject
  Plane/Core/Inc/stm32f4xx_hal_conf.h
  Plane/Core/Src/main.cpp
  Plane/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_i2c.h
  Plane/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_tim.h
  Plane/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
  Plane/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c
  Plane/Plane Debug.launch
  Plane/Plane.ioc
Labels: Critical, RC control, bug

#98 [Integration] Gyro lib to main board
  Libraries/Gyro/bno055.cpp
  Libraries/Gyro/bno055.h
  Libraries/RcChannel/README.txt
  Plane/Core/Inc/stm32f4xx_it.h
  Plane/Core/Src/main.cpp
  Plane/Core/Src/stm32f4xx_hal_msp.c
  Plane/Core/Src/stm32f4xx_it.c
  Plane/Plane.ioc
Labels: Sensors

#95 [ERS] Adding direct engine mode
  Logger/Core/Inc/stm32f4xx_it.h
  Logger/Core/Src/main.cpp
  Logger/Core/Src/stm32f4xx_hal_msp.c
  Logger/Core/Src/stm32f4xx_it.c
  Logger/Logger.ioc
Labels: ERS

#103 [ERS] Change log format
  Libraries/Logger/Logger.cpp
  Logger/.cproject
  Logger/Core/Inc/stm32f4xx_it.h
  Logger/Core/Src/main.cpp
  Logger/Core/Src/stm32f4xx_hal_msp.c
  Logger/Core/Src/stm32f4xx_it.c
  Logger/Logger.ioc
Labels: ERS

#104 [Plane] add omega stab
  Libraries/AirSpeed/MPXV7002.cpp
  Libraries/AirSpeed/MPXV7002.h
  Libraries/PIReg/PIReg.cpp
  Libraries/PIReg/PIReg.h
  Plane/Core/Src/main.cpp
Labels: AFCS
